### PR TITLE
Allows for viewing the repository log when sha1s are missing.

### PR DESCRIPTION
**Pull request by petternilsen**
This is related to my email from earlier.

### CODE REVIEW

**Comment by petternilsen** [comment]
Hey Jens, anything more i need to do on this one?

**Comment by jensl** [comment]
Petter, I'm very sorry it's taken me so long to handle this. I've created https://critic-review.org/r/345 for it, and raised an issue. I can fix that myself, though, so no need for you to do anything (other than nagging me if I still don't land this on master.)

**Comment by petternilsen** [comment]
Cool thanks.

**Comment by jensl** [comment]
Merged (slightly modified).

**Pull request closed without merging**
