### PR TITLE
WiP: support newer git versions

### PR DESCRIPTION
**Pull request by mostynb**
Here's a possible start on a fix for #112.  It's untested, and I still need to figure out where to send/use these environment variables, but just wanted to get the ball rolling.

### CODE REVIEW

**Comment by mostynb** [comment]
Apparently this was fixed in a big rewrite somewhere else.

**Comment by Zitrax** [comment]
Does that mean it's currently fixed on master, stable or somewhere else?

**Comment by jensl** [comment]
It's fixed here: https://critic-review.org/r/371

Not merged to any other branch.

**Comment by trulyliu** [comment]
Is there any ETA of this fix?

> It's fixed here: https://critic-review.org/r/371
> 
> Not merged to any other branch.

**Pull request closed without merging**
